In [4]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5])
print(arr,type(arr),arr2.dtype)
print(arr.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> <U21
(5,)


In [7]:
arr2 = np.array([1,2,3,4,5,"mf"])
print(arr2, arr2.dtype)
print(arr2.shape)

['1' '2' '3' '4' '5' 'mf'] <U21
(6,)


In [10]:
# 2D Array
arr2D = np.array([[1,2,3,],[4,5,6],[7,8,9]])
print(arr2D, arr2D.dtype)
print(arr2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] int64
(3, 3)


In [ ]:
# Creating Array Using BUilt in function


In [13]:
arr1=np.zeros((2,3), dtype="int64") # prefill
print(arr1,arr1.shape)

[[0 0 0]
 [0 0 0]] (2, 3)


In [14]:
arr0=np.ones((2,3), dtype="int64") # prefill
print(arr0,arr0.shape)

[[1 1 1]
 [1 1 1]] (2, 3)


In [15]:
arr0=np.full((3,3), 100) # prefill with value
print(arr0,arr0.shape)

[[100 100 100]
 [100 100 100]
 [100 100 100]] (3, 3)


In [16]:
arr0=np.eye(3) # identity matrix
print(arr0,arr0.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)


In [18]:
# range function range(start,stop , step)
arr0=np.arange(1,10,1) # range elements
print(arr0,arr0.shape)

[1 2 3 4 5 6 7 8 9] (9,)


In [19]:
arr0=np.linspace(1,100,4) # evenly spaced  elements
print(arr0,arr0.shape)

[  1.  34.  67. 100.] (4,)


In [ ]:
#Properties of Numpy

In [23]:
arr = np.array([1,2,3,4,5])
print(arr.shape) #dimension = m* n
print(arr.size) # total elements
print(arr.dtype) #
print(arr.ndim) #

(5,)
5
int64
1


In [24]:
# Float type
float_arr= arr.astype(np.float64)
print(float_arr,float_arr.dtype) 

[1. 2. 3. 4. 5.] float64


In [ ]:
# Different Operations on Arrays

In [29]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape,end="\n \n")

reshaped  = arr.reshape(3,2)
print(reshaped,reshaped.shape)


[[1 2 3]
 [4 5 6]] (2, 3)
 
[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [31]:
flattened = arr.flatten() # 2D -> 1D
print(flattened,flattened.shape)

[1 2 3 4 5 6] (6,)


In [ ]:
# Indexing on 1D & 2D Array

In [35]:
arr = np.array([1,2,3])
print(arr,arr.shape,end="\n \n")
print(f"arr[0] =  {arr[0]}")

[1 2 3] (3,)
 
arr[0] =  1


In [36]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape,end="\n \n")
print(f"arr[0][1] =  {arr[0][1]}")

[[1 2 3]
 [4 5 6]] (2, 3)
 
arr[0][1] =  2


In [40]:
#Fancy Indexing
arr = np.array([1,2,3,4,5,6,7])
idx=[0,5,2]
print(arr[idx])

# Boolean indexing
print(arr[arr>3])
print(arr[arr%2==0])

[1 6 3]
[4 5 6 7]
[2 4 6]


In [43]:
#Slicing (start,end,step)
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[::2])

[2 3 4]
[2 3 4 5 6 7]
[1 2 3 4]
[1 3 5 7]


In [ ]:
#copy vs view 

In [6]:
nums=[1,2,3,4,5,6]
sub_list=nums[1:3]
print(sub_list)
sub_list[0]=200
print(sub_list)
print(nums)


[2, 3]
[200, 3]
[1, 2, 3, 4, 5, 6]


In [11]:
# in numpy
arr=np.array([1,2,3,4,5])
sub_arr=arr[1:3]
print("sub_arr",sub_arr)
print("arr",arr)
sub_arr[0]=200
print("sub_arr",sub_arr)
print("arr",arr)

sub_arr [2 3]
arr [1 2 3 4 5]
sub_arr [200   3]
arr [  1 200   3   4   5]


In [12]:
#Copy in Numpy
arr=np.array([1,2,3,4,5])
sub_arr=arr[1:3].copy()
print("sub_arr",sub_arr)
print("arr",arr)
sub_arr[0]=200
print("sub_arr",sub_arr)
print("arr",arr)

sub_arr [2 3]
arr [1 2 3 4 5]
sub_arr [200   3]
arr [1 2 3 4 5]
