In [1]:
import numpy as np

In [2]:
#Data Type in Numpy

In [3]:
#Integer
arr = np.array([1,2,3,4,5])
print(arr,arr.dtype)

[1 2 3 4 5] int64


In [4]:
#Float
arr = np.array([1,2,3,4,5.5])
print(arr,arr.dtype)

[1.  2.  3.  4.  5.5] float64


In [5]:
#String
arr = np.array([1,2,3,4,5.5,"MF"])
print(arr,arr.dtype)

['1' '2' '3' '4' '5.5' 'MF'] <U32


In [6]:
arr = np.array([1,2,3,4,5,"MF"])
print(arr,arr.dtype)

['1' '2' '3' '4' '5' 'MF'] <U21


In [7]:
#Complex Number (real+img)
arr=np.array([3+5j])
print(arr,arr.dtype)

[3.+5.j] complex128


In [8]:
arr1=np.array([3+5j])
arr2=np.array([3+5j])
arr3=arr1+arr2
print(arr3,arr3.dtype)

[6.+10.j] complex128


In [9]:
#Axes in Multi-dimensional arrays
#1D --> 1 axis (axis 0 -> horizontally )
#2D --> 2 axis(axis 0 -> vertically , axis 1 -> horizontally) 
#3D --> 3 axis (axis 1 -> depth / layers ,axis 1 -> vertically , axis 2 -> horizontally)

In [10]:
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)
print(np.sum(arr2D))
sum_of_col = np.sum(arr2D, axis = 0)
print(sum_of_col)
sum_of_row = np.sum(arr2D, axis = 1)
print(sum_of_row)

# Slicing in 2D Array
print("\n Slicing :- \n",arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]

 Slicing :- 
 [[2]
 [5]]


In [11]:
#3D Array

In [12]:
arr3D=np.array([[[1,2] , [3,4] , [5,6]] , [[7,8] , [9,10] , [11,12]]])
print(arr3D,"\n",arr3D.shape)

#indexing
print(arr3D[1,1,0])

#Slicing
print(arr3D[:,0,:]) #first row from both layers

#Changing Value 
arr3D[:,0,:] =99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] 
 (2, 3, 2)
9
[[1 2]
 [7 8]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [20]:
arr1=np.array([1,2,3,4,5])
print(arr**2)

[ 1  4  9 16 25]


In [23]:
print(arr1+10)
arr2=np.array([5,4,3,2,1])
print(arr1 + arr2)
arr3=arr1 + arr2
print(arr3)

[11 12 13 14 15]
[6 6 6 6 6]
[6 6 6 6 6]


In [ ]:
#BroadCasting
arr2=np.array([5,4,3,2,1,0])
print(arr1 + arr2)

In [27]:
#Normalization

arr=np.array([5,4,3,2,1,0])
mean=np.mean(arr)
print(arr)

std_dev = np.std(arr)

normalized_arr = (arr -     mean)/std_dev
print(normalized_arr)
print(mean)
print(std_dev)
print(np.mean(normalized_arr))

[5 4 3 2 1 0]
[ 1.46385011  0.87831007  0.29277002 -0.29277002 -0.87831007 -1.46385011]
2.5
1.707825127659933
3.700743415417188e-17
