In [ ]:
#Mathematical Function

In [2]:
#Aggregation
import numpy as np

In [7]:
arr = np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))#index val
print(np.argmax(arr)) #index val

print(np.mean(arr))
print(np.median(arr))
print(np.var(arr))
print(np.std(arr))

15
120
1
5
0
4
3.0
3.0
2.0
1.4142135623730951


In [ ]:
#Power Function

In [10]:
arr = np.array([1,2,3,4,5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [ ]:
#Logarithmic Function

In [12]:
arr = np.array([1,2,3])
print(np.log(arr))
print(np.log2(arr))
print(np.log10(arr))
print(np.exp(arr))


[0.         0.69314718 1.09861229]
[0.        1.        1.5849625]
[0.         0.30103    0.47712125]
[ 2.71828183  7.3890561  20.08553692]


In [ ]:
#Rounding

In [22]:
print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))
arr = np.array([1,2,3,4,1,2,3,4,5,6,6,54,433,2])
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

3.0
4.0
3.0
3.0
[  1   2   3   4   5   6  54 433]
[  1   1   2   2   2   3   3   4   4   5   6   6  54 433]
[  1   2   3   4   1   2   3   4   5   6   6  54 433   2]
